name: Continuous integration

permissions:
  contents: read

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.head_commit.author.email }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: cd dashboard && npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
